// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTGwtYvLRSFwq-Y6T9fwPG5skxq9Nqx5o',
    appId: '1:220282962365:web:e1b9512faa93e46de992d4',
    messagingSenderId: '220282962365',
    projectId: 'chat-app-flutter-01',
    authDomain: 'chat-app-flutter-01.firebaseapp.com',
    storageBucket: 'chat-app-flutter-01.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBl3U_2djMUkqHMzHi8-j30qik8_LcYwfg',
    appId: '1:220282962365:android:a1c996e98f619407e992d4',
    messagingSenderId: '220282962365',
    projectId: 'chat-app-flutter-01',
    storageBucket: 'chat-app-flutter-01.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyroYJeDqm2CNaiHRB2CFiZ26MRXjAw_8',
    appId: '1:220282962365:ios:39eacdf0cfe51edce992d4',
    messagingSenderId: '220282962365',
    projectId: 'chat-app-flutter-01',
    storageBucket: 'chat-app-flutter-01.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyroYJeDqm2CNaiHRB2CFiZ26MRXjAw_8',
    appId: '1:220282962365:ios:39eacdf0cfe51edce992d4',
    messagingSenderId: '220282962365',
    projectId: 'chat-app-flutter-01',
    storageBucket: 'chat-app-flutter-01.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTGwtYvLRSFwq-Y6T9fwPG5skxq9Nqx5o',
    appId: '1:220282962365:web:078c67d88a074b23e992d4',
    messagingSenderId: '220282962365',
    projectId: 'chat-app-flutter-01',
    authDomain: 'chat-app-flutter-01.firebaseapp.com',
    storageBucket: 'chat-app-flutter-01.appspot.com',
  );

}